# Generated by Django 3.1.4 on 2020-12-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gulguta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gulguta',
            name='photo',
            field=models.ImageField(default='1', upload_to='gulgute'),
            preserve_default=False,
        ),
    ]
