# Generated by Django 3.1.4 on 2020-12-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gulguta', '0002_gulguta_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gulguta',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gulguta',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
