# Generated by Django 4.2.1 on 2023-05-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gulguta', '0004_eventcategory_eventinstance_delete_gulguta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
