# Generated by Django 4.2.1 on 2023-05-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gulguta', '0005_alter_eventcategory_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinstance',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
    ]
