# Generated by Django 4.2.1 on 2025-04-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gulguta', '0006_alter_eventinstance_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name_plural': 'Event categories'},
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
